#!/usr/bin/env python3
"""Read one sheet of the ridge diptych into data.js (the source image is never shipped).

  python3 trace.py left.png  ../025-ridge-study-left/data.js
  python3 trace.py right.png ../026-ridge-study-right/data.js

What is kept: the sheet size, the mat colour, the box the picture sits in, a half-resolution
TONAL READING with the emulsion grain removed (non-local means), a coarse map of how much fine
streaking each passage holds, and the measured grain law
(grain strength per tone band + its neighbour correlation). The renderer repaints the tonal
reading with brush strokes and re-grows the grain from the law; it never displays this map.
Needs: opencv-python-headless, numpy.
"""
import sys, base64, json
import cv2, numpy as np

src, out = sys.argv[1], sys.argv[2]
bgr = cv2.imread(src)
g = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
H, W = g.shape
mat = [int(v) for v in bgr[5, 5][::-1]]
m = np.abs(g.astype(int) - int(g[5, 5])) > 6
ys = np.where(m.mean(1) > .5)[0]; xs = np.where(m.mean(0) > .5)[0]
x0, x1, y0, y1 = xs.min(), xs.max() + 1, ys.min(), ys.max() + 1
pic = g[y0:y1, x0:x1]
dn = cv2.fastNlMeansDenoising(pic, None, h=10, templateWindowSize=7, searchWindowSize=21)
res = pic.astype(float) - dn

# grain law = the QUIET floor of each tone band (25th percentile of local σ): what is above it is streaking, not grain
loc = np.sqrt(cv2.GaussianBlur(res * res, (0, 0), 6))
bands = list(range(30, 231, 25)); sd = []
for lo in bands:
    k = (dn >= lo - 12) & (dn < lo + 13)
    sd.append(round(float(np.percentile(loc[k], 25)), 2) if k.sum() > 2000 else None)
known = [(b, s) for b, s in zip(bands, sd) if s is not None]
sd = [s if s is not None else min(known, key=lambda t: abs(t[0] - b))[1] for b, s in zip(bands, sd)]
rho = float(((res[:, :-1] * res[:, 1:]).mean() + (res[:-1] * res[1:]).mean()) / 2 / res.var())

# streak energy: band-pass (σ1.5–3) energy the source holds beyond what the denoised reading kept and beyond what
# pure grain puts in that band (c is calibrated on the quietest tenth of the sheet). 1/8 res, ×8 fixed-point.
law = np.interp(dn.astype(float), bands, sd)
bp = lambda im: cv2.GaussianBlur(im, (0, 0), 1.5) - cv2.GaussianBlur(im, (0, 0), 3)
ev = lambda im: cv2.GaussianBlur(bp(im.astype(float)) ** 2, (0, 0), 6)
es, ed, l2 = ev(pic), ev(dn), cv2.GaussianBlur(law * law, (0, 0), 6)
ratio = (es - ed) / l2
c = float(np.percentile(ratio, 10))
tex = np.sqrt(np.clip(es - ed - 1.25 * c * l2, 0, None)) * 3
xw, xh = int(x1 - x0) // 8, int(y1 - y0) // 8
texq = np.clip(cv2.resize(tex, (xw, xh), interpolation=cv2.INTER_AREA) * 8, 0, 255).astype(np.uint8)
tw, th = int(x1 - x0) // 2, int(y1 - y0 + 1) // 2
tone = cv2.resize(dn, (tw, th), interpolation=cv2.INTER_AREA)
data = dict(W=W, H=H, box=[int(x0), int(y0), int(x1 - x0), int(y1 - y0)], mat=mat, tw=tw, th=th,
            grainL=bands, grainSD=sd, grainRho=round(rho, 3),
            xw=xw, xh=xh, tex=base64.b64encode(texq.tobytes()).decode(),
            tone=base64.b64encode(tone.tobytes()).decode())
open(out, 'w').write('// generated by trace.py — tonal reading + grain law of one sheet\nconst SHEET = ' + json.dumps(data) + ';\n')
print(out, data['box'], 'tone', tw, th, 'grain', sd, 'rho', rho)
