// generated by tools/strata-freeze.mjs — do not edit
window.STRATA_FREEZE = {"version":"1.0","fingerprint":"3c7ee01911aef15fba97cdbcf54357a2c2f6ddd7cafe6df1296de91f851bbe0f","commit":"719dbbea267a6eca781ed8fe2f57b9e978a32751","frozenAt":"2026-09-13T12:36:44.190Z"};
