/*
 * traits.js — the token layer: traits, rarity, metadata, and the schedule
 * column every sheet carries.
 *
 *   Strata.VERSION                     the generator version the rarity table is measured against
 *   Strata.traits(state)               [{ trait_type, value }] — the canonical trait list for a token
 *   Strata.rarity(state)               traits with frequency and tier, the information score in bits,
 *                                      the rank against the sampled population, the overall tier
 *   Strata.metadata(state)             ERC-721 style JSON: name, description, attributes, properties
 *   Strata.drawSchedule(hand, state, rect)   the schedule column on the sheet
 *
 * Frequencies come from lib/rarity.js, generated by tools/strata-rarity.mjs
 * from a sampled run of the generator (build only, thousands of seeds). Rarity
 * is therefore measured, not declared, and must be regenerated whenever a
 * generator change moves the distribution.
 */
(function (global) {
  'use strict';

  const VERSION = '1.0';
  const SERIES = 'ISOMETRIC STRATA';

  const TIERS = [
    ['LEGENDARY', 0.01], ['EPIC', 0.04], ['RARE', 0.12], ['UNCOMMON', 0.30], ['COMMON', 1.01],
  ];
  const RANK_TIERS = [
    ['LEGENDARY', 0.01], ['EPIC', 0.05], ['RARE', 0.15], ['UNCOMMON', 0.40], ['COMMON', 1.01],
  ];
  const tierFor = (p, table) => { for (const t of table || TIERS) if (p < t[1]) return t[0]; return 'COMMON'; };

  function partsBucket(n) {
    return n < 60 ? 'SPARSE' : n < 150 ? 'MODERATE' : n < 300 ? 'DENSE' : 'CROWDED';
  }

  function traits(state) {
    const sp = state.spec, sc = state.scene;
    let parts = 0;
    for (const k in sc.counts) parts += sc.counts[k];
    const ten = state.tenets ? state.tenets.filter((t) => t.ok).length + '/' + state.tenets.length : 'NA';
    return [
      { trait_type: 'Style', value: sp.style.key },
      { trait_type: 'Substyle', value: sp.substyle },
      { trait_type: 'Type', value: sp.type },
      { trait_type: 'View', value: sp.view },
      { trait_type: 'Site', value: sp.site },
      { trait_type: 'Paper', value: sp.paper },
      { trait_type: 'Grid', value: sp.grid },
      { trait_type: 'Ink', value: sp.ink },
      { trait_type: 'Palette', value: sp.paletteName },
      { trait_type: 'Detail', value: sp.detail },
      { trait_type: 'Density', value: sp.density },
      { trait_type: 'Shape', value: sp.shape },
      { trait_type: 'Floors', value: String(sp.floors) },
      { trait_type: 'Buildings', value: String(sp.bldgs) },
      { trait_type: 'Scale', value: state.meta.scale },
      { trait_type: 'Tenets', value: ten },
      { trait_type: 'Parts', value: partsBucket(parts) },
    ];
  }

  function rarity(state) {
    const table = global.STRATA_RARITY || null;
    const list = traits(state);
    let bits = 0;
    const out = list.map((t) => {
      const freq = table && table.traits[t.trait_type] ? table.traits[t.trait_type][t.value] : undefined;
      const p = freq === undefined ? null : Math.max(freq, 1 / (table.samples * 2));
      if (p !== null) bits += -Math.log2(p);
      return Object.assign({}, t, { frequency: p, tier: p === null ? 'UNRANKED' : tierFor(p) });
    });
    let rank = null, tier = 'UNRANKED';
    if (table && table.scores && table.scores.length) {
      // scores are the sorted sample; rank = share of the population scoring at least this
      const q = table.scores;
      let lo = 0, hi = q.length;
      while (lo < hi) { const m = (lo + hi) >> 1; if (q[m] < bits) lo = m + 1; else hi = m; }
      rank = Math.max(1 / q.length, (q.length - lo) / q.length);
      tier = tierFor(rank, RANK_TIERS);
    }
    return { traits: out, bits: bits, rank: rank, tier: tier, basis: table ? { samples: table.samples, version: table.version } : null };
  }

  // the curated edition, when one is loaded: seed → edition number
  function edition(state) {
    const E = global.STRATA_EDITION;
    if (!E || !E.seeds) return null;
    const n = E.seeds[String(state.seed)];
    return n ? { number: n, size: E.size } : null;
  }

  function hash(state) {
    return ('00000000' + global.ISO.hash32(VERSION + ':' + state.seed).toString(16)).slice(-8).toUpperCase();
  }

  function metadata(state) {
    const r = rarity(state), sp = state.spec;
    const hex = (c) => '#' + c.map((v) => ('0' + v.toString(16)).slice(-2)).join('');
    const ed = edition(state);
    return {
      name: 'Isometric Strata ' + (ed ? ed.number + '/' + ed.size : '#' + state.seed),
      description: sp.title + ' — a ' + sp.style.key.toLowerCase() + ' ' + sp.type.toLowerCase() + ' on a ' + sp.site.toLowerCase() +
        ' site, drawn as ' + (sp.view === 'AXONOMETRIC' ? 'an axonometric' : 'a plan and section') + ' on ' + sp.paper.toLowerCase() +
        ' paper. Every count in its legend is tallied from the geometry actually drawn' + (state.tenets ? '; its ' + state.tenets.length + ' tenets are checked over the drawn scene (' + r.traits.find((t) => t.trait_type === 'Tenets').value + ').' : '.'),
      external_url: 'https://dmaris70.github.io/generative-art/projects/011-isometric-strata/?seed=' + state.seed,
      attributes: r.traits.map((t) => ({ trait_type: t.trait_type, value: t.value, rarity: t.frequency, tier: t.tier })),
      properties: {
        series: SERIES, generator: VERSION, fingerprint: global.STRATA_FREEZE ? global.STRATA_FREEZE.fingerprint : null,
        commit: global.STRATA_FREEZE ? global.STRATA_FREEZE.commit : null,
        seed: state.seed, hash: hash(state), dwg: sp.dwg, project: sp.project,
        edition: ed,
        rarity: { bits: Math.round(r.bits * 100) / 100, rank: r.rank, tier: r.tier, basis: r.basis },
        variables: {
          floors: sp.floors, floorHeight: Math.round(sp.floorH * 100) / 100, buildings: sp.bldgs, shape: sp.shape,
          detail: sp.detailN, plot: { w: Math.round(sp.plot.w * 10) / 10, d: Math.round(sp.plot.d * 10) / 10 },
          palette: sp.palette.colors.map(hex), cut: sp.view === 'AXONOMETRIC' ? null : Math.round(state.ortho.cutZ * 100) / 100,
        },
        legend: Object.assign({}, state.scene.counts),
        tenets: state.tenets ? state.tenets.map((t) => ({ name: t.name, ok: t.ok })) : null,
      },
    };
  }

  // ---- the schedule column ----
  function drawSchedule(hand, state, R) {
    const sp = state.spec;
    const r = rarity(state);
    const TXT = { color: [48, 54, 64], alpha: 215 }, DIM = { color: [84, 90, 102], alpha: 170 };
    const RULE = global.Sheet.CHROME2, BOX = global.Sheet.CHROME;
    const x0 = R.x + 10, x1 = R.x + R.w - 10;
    let y = R.y + 10;
    hand.rect(R.x, R.y, R.w, R.h, BOX);
    hand.text('SCHEDULE', x0, y, 13, TXT);
    y += 20;
    hand.line([[x0, y], [x1, y]], RULE);
    y += 10;

    const row = (k, v, size) => {
      const s = size || 8.5;
      hand.text(k, x0, y, s * 0.88, DIM);
      hand.text(String(v), x1, y, s, TXT, { align: 'right' });
      y += 15;
    };
    const section = (name) => {
      y += 6;
      hand.text(name, x0, y, 8, DIM);
      hand.line([[x0 + hand.textWidth(name, 8) + 8, y + 4], [x1, y + 4]], { color: [58, 64, 74], alpha: 70, weight: 0.6, wob: 0.3 });
      y += 16;
    };
    const bar = (frac, xa, xb, yy) => {
      const w = (xb - xa) * Math.max(0.02, Math.min(1, frac));
      hand.rect(xa, yy, xb - xa, 3.5, { color: [58, 64, 74], alpha: 60, weight: 0.5, wob: 0.2 });
      hand.rect(xa, yy, w, 3.5, null, { color: [58, 64, 74], alpha: 190, mode: 'flat' });
    };

    // token
    section('TOKEN');
    row('SERIES', SERIES);
    const ed = edition(state);
    if (ed) row('EDITION', ed.number + ' / ' + ed.size);
    row('TOKEN', '#' + state.seed);
    row('DWG', sp.dwg);
    const fz = global.STRATA_FREEZE;
    row('GENERATOR', 'V' + VERSION + (fz && fz.fingerprint ? '  ' + fz.fingerprint.slice(0, 8).toUpperCase() : ''));
    row('HASH', hash(state));
    row('SCORE', r.bits.toFixed(1) + ' BITS');
    row('RANK', r.rank === null ? 'UNRANKED' : 'TOP ' + (r.rank * 100 < 1 ? (r.rank * 100).toFixed(1) : Math.ceil(r.rank * 100)) + '%');
    row('TIER', r.tier);
    bar(r.bits / 40, x0, x1, y - 2);
    y += 8;

    // traits
    section('TRAITS');
    for (const t of r.traits) {
      hand.text(t.trait_type.toUpperCase(), x0, y, 7.5, DIM);
      hand.text(t.value, x1, y, 8.5, TXT, { align: 'right' });
      y += 12;
      const p = t.frequency;
      bar(p === null ? 0 : Math.min(1, -Math.log2(p) / 8), x0, x0 + 90, y + 1);
      hand.text(p === null ? '—' : (p * 100 < 1 ? (p * 100).toFixed(1) : Math.round(p * 100)) + '%  ' + t.tier, x1, y - 1, 7, DIM, { align: 'right' });
      y += 14;
    }

    // variables
    section('VARIABLES');
    row('SEED', state.seed);
    row('FLOORS / FLOOR H', sp.floors + ' / ' + sp.floorH.toFixed(2) + ' M');
    row('HEIGHT', (sp.floors * sp.floorH).toFixed(1) + ' M');
    row('PLOT', sp.plot.w.toFixed(1) + ' X ' + sp.plot.d.toFixed(1) + ' M');
    row('BUILDINGS / SHAPE', sp.bldgs + ' / ' + sp.shape);
    row('DETAIL / DENSITY', sp.detailN + ' / ' + sp.density);
    if (sp.view !== 'AXONOMETRIC') row('PLAN CUT', '+' + state.ortho.cutZ.toFixed(2) + ' M');
    row('SCALE', state.meta.scale);
    row('PALETTE', sp.paletteName);
    const cols = sp.palette.colors.slice(0, 5);
    for (let i = 0; i < cols.length; i++) {
      const c = cols[i];
      const sx = x0 + i * ((x1 - x0) / 5);
      hand.rect(sx, y, 14, 10, RULE, { color: c, alpha: 220, mode: 'flat' });
      hand.text('#' + c.map((v) => ('0' + v.toString(16)).slice(-2)).join('').toUpperCase(), sx, y + 13, 5.5, DIM);
    }
    y += 32;

    // tenets
    if (state.tenets) {
      section('TENETS');
      for (const t of state.tenets) row(t.name, t.ok ? 'PASS' : 'FAIL');
    }

    // counts: the legend again, in the token's own record
    section('COUNTS');
    const leg = state.meta.legend || [];
    const half = Math.ceil(leg.length / 2);
    const yc = y;
    for (let i = 0; i < leg.length; i++) {
      const col = i < half ? 0 : 1;
      const yy = yc + (i % half) * 13;
      const xa = col === 0 ? x0 : x0 + (x1 - x0) / 2 + 6, xb = col === 0 ? x0 + (x1 - x0) / 2 - 6 : x1;
      hand.text(leg[i].name, xa, yy, 7, DIM);
      hand.text(String(leg[i].count), xb, yy, 8, TXT, { align: 'right' });
    }
    y = yc + half * 13 + 4;

    // basis
    y += 6;
    hand.line([[x0, y], [x1, y]], RULE);
    y += 8;
    hand.text(r.basis ? 'RARITY BASIS: ' + r.basis.samples + ' SAMPLES, V' + r.basis.version : 'RARITY BASIS: NONE LOADED', x0, y, 6.5, DIM);
    y += 11;
    hand.text('COUNTS AND TENETS FROM THE DRAWN SCENE', x0, y, 6.5, DIM);
  }

  global.Strata = global.Strata || {};
  Object.assign(global.Strata, { VERSION: VERSION, SERIES: SERIES, traits: traits, rarity: rarity, metadata: metadata, edition: edition, drawSchedule: drawSchedule, tierFor: tierFor });
})(window);
