#!/usr/bin/env node
// strata-rarity.mjs — measure the Isometric Strata trait distribution.
//
// Builds (never paints) thousands of seeds through the engine in Node, tallies
// every trait value's frequency, computes each sample's information score, and
// writes projects/011-isometric-strata/lib/rarity.js — the table the sheets'
// schedule column and the metadata export read. Re-run after any generator
// change that could move the distribution; bump Strata.VERSION when you do.
//
//   node tools/strata-rarity.mjs [samples=4000] [firstSeed=1]

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const proj = path.join(root, 'projects', '011-isometric-strata');
const samples = Number(process.argv[2]) || 4000;
const first = Number(process.argv[3]) || 1;

// the engine attaches itself to `window`; give it one
globalThis.window = globalThis;
const files = [
  'assets/strokefont.js',
  'projects/011-isometric-strata/lib/core.js', 'projects/011-isometric-strata/lib/plan.js',
  'projects/011-isometric-strata/lib/render.js', 'projects/011-isometric-strata/lib/paper.js',
  'projects/011-isometric-strata/lib/sheet.js', 'projects/011-isometric-strata/lib/site.js',
  ...fs.readdirSync(path.join(proj, 'lib', 'styles')).map((f) => 'projects/011-isometric-strata/lib/styles/' + f),
  'projects/011-isometric-strata/lib/strata.js', 'projects/011-isometric-strata/lib/traits.js',
];
for (const f of files) vm.runInThisContext(fs.readFileSync(path.join(root, f), 'utf8'), { filename: f });

const Strata = globalThis.Strata;
const counts = {};
const scores = [];
const t0 = Date.now();
const all = [];
for (let i = 0; i < samples; i++) {
  const state = Strata.build({ seed: (first + i) >>> 0 });
  const tr = Strata.traits(state);
  all.push(tr);
  for (const t of tr) {
    counts[t.trait_type] = counts[t.trait_type] || {};
    counts[t.trait_type][t.value] = (counts[t.trait_type][t.value] || 0) + 1;
  }
  if (i % 500 === 499) process.stderr.write(`${i + 1}/${samples}\n`);
}
const traits = {};
for (const k in counts) {
  traits[k] = {};
  for (const v in counts[k]) traits[k][v] = counts[k][v] / samples;
}
for (const tr of all) {
  let bits = 0;
  for (const t of tr) bits += -Math.log2(traits[t.trait_type][t.value]);
  scores.push(Math.round(bits * 1000) / 1000);
}
scores.sort((a, b) => a - b);
// keep a thinned quantile ladder so the file stays small
const keep = 400;
const ladder = [];
for (let i = 0; i < keep; i++) ladder.push(scores[Math.min(scores.length - 1, Math.floor((i / (keep - 1)) * (scores.length - 1)))]);

const out = {
  version: Strata.VERSION, samples: samples, firstSeed: first, generatedAt: new Date().toISOString(),
  traits: traits, scores: ladder,
  summary: { minBits: scores[0], medianBits: scores[Math.floor(scores.length / 2)], maxBits: scores[scores.length - 1] },
};
const js = '// generated by tools/strata-rarity.mjs — do not edit; re-run after generator changes\n' +
  'window.STRATA_RARITY = ' + JSON.stringify(out) + ';\n';
fs.writeFileSync(path.join(proj, 'lib', 'rarity.js'), js);
console.log(`wrote lib/rarity.js: ${samples} samples in ${Date.now() - t0} ms; bits min/median/max ${out.summary.minBits}/${out.summary.medianBits}/${out.summary.maxBits}`);
for (const k of ['Style', 'View', 'Site', 'Paper', 'Tenets', 'Parts', 'Buildings']) {
  console.log(k + ': ' + Object.entries(traits[k]).sort((a, b) => b[1] - a[1]).map(([v, p]) => `${v} ${(p * 100).toFixed(1)}%`).join(' · '));
}
