#!/usr/bin/env node
// strata-freeze.mjs — fingerprint the Isometric Strata generator, or verify it.
//
// The fingerprint is a SHA-256 over every file that can change a drawing —
// the engine, the styles, the token layer, the stroke font, the vendored p5 —
// in a fixed order. `freeze` writes lib/freeze.js (loaded by the pages so the
// schedule prints the fingerprint) and edition/freeze-<version>.json (the
// record: version, git commit, per-file hashes, the rarity table's and the
// edition's hashes). `verify` recomputes and fails if anything differs.
//
//   node tools/strata-freeze.mjs freeze
//   node tools/strata-freeze.mjs verify

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const proj = 'projects/011-isometric-strata';
const mode = process.argv[2] || 'verify';

// everything that can change a drawing, in a fixed order; freeze.js itself is excluded
const FILES = [
  'assets/strokefont.js', 'assets/genart.js',
  `${proj}/vendor/p5-1.9.4.min.js`, `${proj}/vendor/lil-gui-0.19.umd.min.js`,
  ...['core', 'plan', 'render', 'paper', 'sheet', 'site', 'strata', 'traits'].map((f) => `${proj}/lib/${f}.js`),
  ...fs.readdirSync(path.join(root, proj, 'lib', 'styles')).sort().map((f) => `${proj}/lib/styles/${f}`),
  `${proj}/sketch.js`, `${proj}/index.html`,
];
const sha = (p) => crypto.createHash('sha256').update(fs.readFileSync(path.join(root, p))).digest('hex');
const files = {};
const all = crypto.createHash('sha256');
for (const f of FILES) { files[f] = sha(f); all.update(f + ':' + files[f] + '\n'); }
const fingerprint = all.digest('hex');

// the version the token layer declares
const traits = fs.readFileSync(path.join(root, proj, 'lib', 'traits.js'), 'utf8');
const version = (traits.match(/const VERSION = '([^']+)'/) || [])[1];
const freezeJs = path.join(root, proj, 'lib', 'freeze.js');
const record = path.join(root, proj, 'edition', `freeze-${version}.json`);

if (mode === 'freeze') {
  let commit = null;
  try { commit = execSync('git rev-parse HEAD', { cwd: root }).toString().trim(); } catch (e) { /* no git */ }
  const out = {
    series: 'ISOMETRIC STRATA', version, fingerprint, commit, frozenAt: new Date().toISOString(),
    files,
    rarity: sha(`${proj}/lib/rarity.js`),
    edition: fs.existsSync(path.join(root, proj, 'edition', 'edition-256.json')) ? sha(`${proj}/edition/edition-256.json`) : null,
    note: 'Any change to a listed file changes the fingerprint; the rarity table and the edition are only valid for this fingerprint.',
  };
  fs.writeFileSync(record, JSON.stringify(out, null, 1) + '\n');
  fs.writeFileSync(freezeJs, `// generated by tools/strata-freeze.mjs — do not edit\nwindow.STRATA_FREEZE = ${JSON.stringify({ version, fingerprint, commit, frozenAt: out.frozenAt })};\n`);
  console.log(`frozen v${version}: fingerprint ${fingerprint.slice(0, 16)}… over ${FILES.length} files; commit ${commit}`);
} else {
  if (!fs.existsSync(record)) { console.error(`no freeze record for v${version}`); process.exit(2); }
  const rec = JSON.parse(fs.readFileSync(record, 'utf8'));
  const changed = FILES.filter((f) => rec.files[f] !== files[f]);
  const rarityOk = rec.rarity === sha(`${proj}/lib/rarity.js`);
  const editionOk = !rec.edition || rec.edition === sha(`${proj}/edition/edition-256.json`);
  if (rec.fingerprint === fingerprint && rarityOk && editionOk) {
    console.log(`verified v${version}: fingerprint ${fingerprint.slice(0, 16)}… matches the freeze of ${rec.frozenAt} (commit ${rec.commit})`);
  } else {
    console.error(`FROZEN GENERATOR CHANGED: fingerprint ${fingerprint.slice(0, 16)}… vs ${rec.fingerprint.slice(0, 16)}…`);
    for (const f of changed) console.error('  changed: ' + f);
    if (!rarityOk) console.error('  changed: lib/rarity.js');
    if (!editionOk) console.error('  changed: edition/edition-256.json');
    process.exit(1);
  }
}
