# Transcribes the source sheet into data.js: colour regions (light→dark glazes are decided
# by the sketch), edge hardness per region, and the graphite underdrawing as polylines.
# usage: python3 trace.py src.png 48 16   (the source image is not shipped)
import sys, json, numpy as np, cv2
from scipy import ndimage as ndi
src = sys.argv[1]; K = int(sys.argv[2]) if len(sys.argv) > 2 else 40; MINA = int(sys.argv[3]) if len(sys.argv) > 3 else 50
bgr = cv2.imread(src); H, W = bgr.shape[:2]
sm = cv2.bilateralFilter(bgr, 7, 28, 5)
lab = cv2.cvtColor(sm, cv2.COLOR_BGR2LAB).astype(np.float32)
rng = np.random.default_rng(7)
samp = lab.reshape(-1, 3)[rng.choice(W * H, 120000, replace=False)]
_, _, cen = cv2.kmeans(samp, K, None, (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 40, .5), 4, cv2.KMEANS_PP_CENTERS)
flat = lab.reshape(-1, 3); q = np.empty(W * H, np.int32)
for s in range(0, W * H, 400000):
    d = ((flat[s:s + 400000, None, :] - cen[None]) ** 2).sum(2); q[s:s + 400000] = d.argmin(1)
q = q.reshape(H, W)
q = cv2.medianBlur(q.astype(np.uint8), 3).astype(np.int32)

def components(q):
    lbl = np.zeros(q.shape, np.int32); n = 0
    for k in range(K):
        l, c = ndi.label(q == k); lbl[l > 0] = l[l > 0] + n; n += c
    return lbl, n
lbl, n = components(q)
area = np.bincount(lbl.ravel(), minlength=n + 1)
small = area[lbl] < MINA
idx = ndi.distance_transform_edt(small, return_distances=False, return_indices=True)
q = q[idx[0], idx[1]]
lbl, n = components(q); area = np.bincount(lbl.ravel(), minlength=n + 1)
print('regions', n)

g = cv2.GaussianBlur(cv2.cvtColor(bgr, cv2.COLOR_BGR2LAB).astype(np.float32), (0, 0), 1.2)
grad = sum(np.hypot(cv2.Sobel(g[..., i], cv2.CV_32F, 1, 0), cv2.Sobel(g[..., i], cv2.CV_32F, 0, 1)) for i in range(3)) / 3
rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
objs = ndi.find_objects(lbl); out = []
for i, sl in enumerate(objs, 1):
    if sl is None or area[i] < MINA: continue
    y0, x0 = max(sl[0].start - 1, 0), max(sl[1].start - 1, 0)
    m = (lbl[y0:sl[0].stop + 1, x0:sl[1].stop + 1] == i).astype(np.uint8)
    cs, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    c = max(cs, key=cv2.contourArea)
    core = cv2.erode(m, np.ones((3, 3), np.uint8)); core = core if core.sum() > 8 else m
    col = np.median(rgb[y0:sl[0].stop + 1, x0:sl[1].stop + 1][core > 0], 0)
    hard = float(np.mean(grad[c[:, 0, 1] + y0, c[:, 0, 0] + x0]))
    p = cv2.approxPolyDP(c, 0.7 if area[i] < 400 else 1.0, True)[:, 0, :] + [x0, y0]
    if len(p) < 3: continue
    out.append([int(area[i]), [int(v) for v in col], hard, p.ravel().tolist()])
out.sort(key=lambda r: -r[0])
hs = np.array([r[2] for r in out]); lo, hi = np.percentile(hs, 10), np.percentile(hs, 92)
for r in out: r[2] = int(np.clip((r[2] - lo) / (hi - lo), 0, 1) * 9 + .5)

# graphite: thin dark low-chroma lines riding over pale passages
L = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
bh = cv2.morphologyEx(L, cv2.MORPH_BLACKHAT, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7)))
hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
pale = cv2.GaussianBlur(L, (0, 0), 6) > 150
line = (bh > 14) & pale & (hsv[..., 1] < 90)
line = ndi.binary_closing(line, iterations=1)
l, c = ndi.label(line, np.ones((3, 3))); a = np.bincount(l.ravel()); line = (a[l] >= 6) & (a[l] < 900) & (l > 0)
line = ndi.binary_dilation(line, iterations=3)          # bridge the dots of a dragged pencil
sk = cv2.ximgproc.thinning(line.astype(np.uint8) * 255) if hasattr(cv2, 'ximgproc') else None
if sk is None:
    from skimage.morphology import skeletonize
    sk = skeletonize(line).astype(np.uint8)
ys, xs = np.nonzero(sk); pts = set(zip(xs.tolist(), ys.tolist())); lines = []
N8 = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (1, -1), (-1, 1), (-1, -1)]
def deg(p): return sum((p[0] + dx, p[1] + dy) in pts for dx, dy in N8)
def walk(p):
    path = [p]; pts.discard(p)
    while True:
        nx = [(p[0] + dx, p[1] + dy) for dx, dy in N8 if (p[0] + dx, p[1] + dy) in pts]
        if not nx: return path
        p = nx[0]; pts.discard(p); path.append(p)
for p in sorted(pts, key=lambda p: deg(p)):
    if p in pts:
        w = walk(p)
        if len(w) >= 14:
            a = cv2.approxPolyDP(np.array(w, np.int32)[:, None, :], 1.6, False)[:, 0, :]
            lines.append(a.ravel().tolist())
print('pencil lines', len(lines), 'points', sum(len(r[3]) for r in out) // 2)
with open('data.js', 'w') as f:
    f.write('// generated by trace.py — [area, [r,g,b], edge hardness 0-9, [x,y,...]] in source px, largest first\n')
    f.write('const SRC_W=%d, SRC_H=%d;\nconst REGIONS=%s;\nconst PENCIL=%s;\n' % (W, H, json.dumps(out, separators=(',', ':')), json.dumps(lines, separators=(',', ':'))))
